<template>
    <div class="flex flex-col space-y-8">
        <div class="home -mt-10 text-4xl py-6 font-bold">
            Home: <span class="text-gray-400">all</span> <span class="text-gray-200"> tasks</span>

        </div>
        <!-- Id (This should be auto generated by the application at the point of saving a task) <br>
        Title <br>
        Description <br>
        Date Added (This should be automatically generated by the task app and should pick the current date and time
        when the task is added) <br>
        Deadline (Date) <br>
        Date <br>
        Completed (Date) <br> -->

        <form v-on:submit.prevent="" class="space-y-2">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task title...">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task description...">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task due date...">
            <!-- <a-space direction="vertical" :size="12">
                <a-date-picker v-model:value="value1" />
            </a-space> -->

            <button class="w-full p-2 border-2 border-gray-400">Add task</button>

        </form>
        <div>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Completed</th>
                        <th>Created At</th>
                        <th>Deadline</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="task in tasks" :key="task.id">
                        <td>{{ task.id }}</td>
                        <td>{{ task.title }}</td>
                        <td>{{ task.completed }}</td>
                        <td>{{ task.created_at }}</td>
                        <td>{{ task.deadline }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
import { Dayjs } from 'dayjs';
export default {
    computed: {
        tasks() {
            return this.$store.state.toDoList;
        }
    },

}
</script>

<style>
</style>