<template>
    <div class="flex flex-col space-y-8">
        <div class="home -mt-10 text-4xl py-6 font-bold">
            Home: <span class="text-gray-400">all</span> <span class="text-gray-200"> tasks</span>

        </div>
        <!-- Id (This should be auto generated by the application at the point of saving a task) <br>
        Title <br>
        Description <br>
        Date Added (This should be automatically generated by the task app and should pick the current date and time
        when the task is added) <br>
        Deadline (Date) <br>
        Date <br>
        Completed (Date) <br> -->

        <form v-on:submit.prevent="addNewTask()" class="space-y-2">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task title..."
                v-model.lazy="newTask.title">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task description..."
                v-model.lazy="newTask.description">
            <input type="date" class="w-full p-2 border-2 border-gray-400" placeholder="Task deadline..."
                v-model.lazy="newTask.deadline">

            <button class="w-full p-2 border-2 border-gray-400">{{this.editing ? 'Update' : 'Add'}}</button>

        </form>
        <div>
            <table v-if="tasks.length">
                <thead>
                    <tr>
                        <th class="p-4">Done</th>
                        <th class="p-4">ID</th>
                        <th class="p-4">Title</th>
                        <th class="p-4">Created At</th>
                        <th class="p-4">Completed</th>
                        <th class="p-4">Deadline</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="task in tasks" :key="task.id" v-bind:class="{completed: task.completed}">
                        <td class="p-4 cursor-pointer">
                            <!-- <button class="bg-sky-500 hover:bg-sky-700 text-white font-bold py-2 px-4 rounded"
                                @click="completeTask(task)">
                                Done
                            </button> -->
                            <input class="cursor-pointer bg-red-100 border-red-300 text-red-500 focus:ring-red-200" type="checkbox" v-model="task.completed" @click="completeTask(task)">
                        </td>
                        <td class="p-4">{{ task.id }}</td>
                        <td class="p-4">{{ task.title }}</td>
                        <td class="p-4">{{ task.date_added }}</td>
                        <td class="p-4">{{ task.completed === true ? new Date().getFullYear() + '-' + (new Date().getMonth() + 1) + '-' + new Date().getDate() : 'ongoing' }}</td>
                        
                        <td class="p-4">{{ task.deadline }}</td>

                        <td class="p-4">
                            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                                @click="setTask(task)">
                                Edit
                            </button>
                        </td>
                        <td class="p-4">
                            <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
                                @click="deleteTask(task.id)">
                                Delete
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
import { onMounted } from '@vue/runtime-core';
import { mapState } from 'vuex';
export default {
    computed: {
        // tasks() {
        //     return this.$store.state.toDoList;
        // }
        ...mapState({
            tasks: 'toDoList'
        })
    },
    watch: {
        updatedTask: function (newTask) {
            this.updateTask(newTask);
        }
    },
    data: () => ({
        newTask: {
            title: '',
            description: '',
            due_date: '',
            date_added: new Date().getFullYear() + '-' + (new Date().getMonth() + 1) + '-' + new Date().getDate(),
            deadline: '',
            completed: false,
            completed_date: 'ongoing'
        },
        editedTask: null,
        editing: false,
    }),
    methods: {
        addNewTask() {
            // console.log(this.newTask);
            // dispatch the action to add the new task

            if (this.editedTask === null) {

            this.$store.dispatch('addNewTask', this.newTask);
            this.newTask = {
                title: '',
                description: '',
                due_date: '',
                date_added: new Date().getFullYear() + '-' + (new Date().getMonth() + 1) + '-' + new Date().getDate(),
                deadline: '',
                completed: false,
                completed_date: 'ongoing'
            }
            } else {
                this.$store.dispatch('editTask', this.editedTask);
                this.editedTask = null;
            }
            this.clearFields();
        },
        clearFields(){
            this.newTask = {
                title: '',
                description: '',
                due_date: '',
                date_added: new Date().getFullYear() + '-' + (new Date().getMonth() + 1) + '-' + new Date().getDate(),
                deadline: '',
                completed: false,
                completed_date: 'ongoing'
            },
            this.editing = false;
        },
        deleteTask(task) {
            this.$store.dispatch('deleteTask', task);
            // console.log('delete', task.id);
        },
        completeTask(task) {
            this.$store.dispatch('completeTask', task);
            // console.log('complete', task.id);
        },
        getPosts() {
            this.$store.dispatch('initPosts');
        },
        setTask(task) {
            // this.$store.dispatch('setTask', { id, task });
            this.editing = true;
            this.newTask = task;
            this.editedTask = task;
        }
        
    },
    created() {
        this.getPosts();
    }
}
</script>

<style scoped>
.completed {
    background-color: #ffffff;
    /* text-decoration: line-through; */
    color: #d0d0d0;
}
</style>