<template>
    <div class="flex flex-col space-y-8">
        <div class="home -mt-10 text-4xl py-6 font-bold">
            Home: <span class="text-gray-400">all</span> <span class="text-gray-200"> tasks</span>

        </div>
        <!-- Id (This should be auto generated by the application at the point of saving a task) <br>
        Title <br>
        Description <br>
        Date Added (This should be automatically generated by the task app and should pick the current date and time
        when the task is added) <br>
        Deadline (Date) <br>
        Date <br>
        Completed (Date) <br> -->

        <form v-on:submit.prevent="addNewTask()" class="space-y-2">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task title..."
                v-model="newTask.title">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task description..."
                v-model="newTask.description">
            <input type="text" class="w-full p-2 border-2 border-gray-400" placeholder="Task due date..."
                v-model="newTask.due_date">

            <button class="w-full p-2 border-2 border-gray-400">Add task</button>

        </form>
        <div>
            <table>
                <thead>
                    <tr>
                        <th class="p-4">Done</th>
                        <th class="p-4">ID</th>
                        <th class="p-4">Title</th>
                        <th class="p-4">Completed</th>
                        <th class="p-4">Created At</th>
                        <th class="p-4">Deadline</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="task in tasks" :key="task.id">
                        <td class="p-4">
                            <input type="checkbox" v-model="task.completed">
                        </td>
                        <td class="p-4">{{ task.id }}</td>
                        <td class="p-4">{{ task.title }}</td>
                        <td class="p-4">{{ task.completed }}</td>
                        <td class="p-4">{{ task.created_at }}</td>
                        <td class="p-4">{{ task.deadline }}</td>

                        <td class="p-4">
                            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                                @click="completeTask(task)">
                                Edit
                            </button>
                        </td>
                        <td class="p-4">
                            <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
                                @click="deleteTask">
                                Delete
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
import { Dayjs } from 'dayjs';
export default {
    computed: {
        tasks() {
            return this.$store.state.toDoList;
        }
    },
    data: () => ({
        newTask: {
            title: '',
            description: '',
            due_date: '',
            created_at: new Date().getFullYear() + '-' + (new Date().getMonth() + 1) + '-' + new Date().getDate(),
            deadline: '',
            completed: false
        }
    }),
    methods: {
        addNewTask() {
            console.log(this.newTask);
            // dispatch the action to add the new task
            this.$store.dispatch('addNewTask', this.newTask);
            this.newTask = {
                title: '',
                description: '',
                due_date: '',
                created_at: new Date().getFullYear() + '-' + (new Date().getMonth() + 1) + '-' + new Date().getDate(),
                deadline: '',
                completed: false
            }
        },
        deleteTask() {
            this.$store.dispatch('deleteTask', this.task);
        },
    }

}
</script>

<style>
</style>